# Generated by Django 4.1.7 on 2023-03-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('dob', models.TextField(default='blank', max_length=120)),
                ('obs', models.TextField(default='blank', max_length=120)),
                ('senha', models.TextField(default='blank', max_length=120)),
                ('endereco', models.TextField(default='blank', max_length=120)),
            ],
        ),
    ]
