# Generated by Django 4.1.7 on 2023-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(default='describe the product', max_length=120)),
                ('tipo', models.BooleanField(default=1)),
                ('obs', models.CharField(default='Blank', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
