# Generated by Django 4.1.7 on 2023-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diastrb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=120)),
                ('local', models.CharField(default='MC House', max_length=120)),
                ('tipo', models.BooleanField(default=1)),
                ('obs', models.CharField(default='Blank', max_length=120)),
            ],
        ),
    ]
