# Generated by Django 4.1.7 on 2023-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogz',
            name='donoid',
            field=models.CharField(default='blank', max_length=10),
        ),
    ]
