# Generated by Django 4.1.7 on 2023-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diastrb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diastrb',
            name='ano',
            field=models.CharField(default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='diastrb',
            name='mes',
            field=models.CharField(default='Blank', max_length=2),
        ),
        migrations.AlterField(
            model_name='diastrb',
            name='dia',
            field=models.CharField(default='Blank', max_length=2),
        ),
    ]
